module.exports = {
  branchPrefix: 'renovate-github/',
  dryRun: false,
  gitAuthor: 'Renovate Bot GitHub <bot@renovateapp.com>',
  platform: 'github',
  repositories: ['ng-easy/platform', 'ng-easy/renovate-config'],
  includeForks: false,
  dependencyDashboard: true,
  onboarding: false,
  autodiscover: false,
  trustLevel: 'high',
  allowPostUpgradeCommandTemplating: true,
  allowedPostUpgradeCommands: [
    '^npm ci',
    '^npm i',
    '^npx ng update',
    '^npx nx migrate',
    '^rm -f migrations.json',
    '^npx nx workspace-lint$',
    '^npx nx run-many --target=lint --all --parallel --fix --skip-nx-cache$',
  ],
};
