name: CI
on:
  push:
    branches:
      - main
      - 'renovate-github/**'
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x

      - name: NPM
        uses: ng-easy/npm-setup@v2.0.6

      - name: Lint
        run: npm run lint
