name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  ci:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false # Needed so that semantic release can use the admin token

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Personal access token with repo permissions

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ github.ref }}
          force: true
          tags: true
          github_token: ${{ secrets.RELEASE_TOKEN }}
